### From MLG to nn

In [1]:
import torch
import numpy as np



In [20]:
np.random.seed(41)





X = torch.from_numpy(np.random.exponential(scale = 15,size = (15,4)))
betas = torch.tensor([[1.,3.,15.,-2.]], dtype=torch.float64)
b0 = torch.tensor([[2.]], dtype=torch.float64)
y = X @ betas.t() + b0


In [21]:
y

tensor([[ 261.2693],
        [  60.0724],
        [ 144.7189],
        [ 167.7342],
        [ 329.7891],
        [ 182.9445],
        [ 110.9456],
        [  79.9302],
        [1742.1217],
        [ 450.8701],
        [ 145.6723],
        [ 352.7420],
        [ 117.3411],
        [ 133.8173],
        [ 663.0963]], dtype=torch.float64)

/tmp/ipykernel_11399/301197645.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  y.grad()


TypeError: 'NoneType' object is not callable

### Nothing new until now

In [123]:
from torch.utils.data import TensorDataset
dataset = TensorDataset(X, y)

from torch.utils.data import DataLoader


train_loader = DataLoader(dataset, batch_size = 25, shuffle=True)



In [13]:
#https://www.analyticsvidhya.com/blog/2021/08/linear-regression-and-gradient-descent-in-pytorch/
def rmse(y,y_hat):
    return torch.sqrt(((torch.pow(y-y_hat,2))/torch.numel(y)).sum())

#loss =  

In [22]:
w = torch.randn(1,int(X[1].numel()), requires_grad=True, dtype=torch.float64)

b =  torch.randn(1, requires_grad=True, dtype=torch.float64)

b

tensor([-1.7254], dtype=torch.float64, requires_grad=True)

In [23]:
def LinearReg(inputs):
    y_t = inputs @ w.transpose(0,1)  + b
    return y_t
    

In [24]:
#LinearReg(X)
loss = rmse(y,LinearReg(X))
loss.backward()
loss

tensor(505.0479, dtype=torch.float64, grad_fn=<SqrtBackward>)

In [25]:

w.grad.zero_()
b.grad.zero_()

tensor([0.], dtype=torch.float64)

In [31]:
learning_rate = 0.001
for i in range(1000):    
    y_hat = LinearReg(X)
    loss = rmse(y,y_hat)
    loss.backward()
    with torch.no_grad():
        w -= learning_rate * w.grad
        b -= learning_rate * b.grad
        w.grad.zero_()
        b.grad.zero_()
    if i == 50 or i==900:
        print(loss)

tensor(0.6461, dtype=torch.float64, grad_fn=<SqrtBackward>)
tensor(0.6461, dtype=torch.float64, grad_fn=<SqrtBackward>)


In [33]:
w

tensor([[ 1.0184,  3.0285, 15.0179, -1.9772]], dtype=torch.float64,
       requires_grad=True)

In [28]:
y

tensor([[ 261.2693],
        [  60.0724],
        [ 144.7189],
        [ 167.7342],
        [ 329.7891],
        [ 182.9445],
        [ 110.9456],
        [  79.9302],
        [1742.1217],
        [ 450.8701],
        [ 145.6723],
        [ 352.7420],
        [ 117.3411],
        [ 133.8173],
        [ 663.0963]], dtype=torch.float64)

In [60]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression().fit(df.data,df.target)

In [62]:
from sklearn.metrics import mean_squared_error

mean_squared_error(reg.predict(df.data),df.target)

2859.6903987680657

In [92]:
class LinearReg():
   def __init__(self):
      self.w = torch.randn(1,int(X[1].numel()), requires_grad=True)
      self.b = torch.randn(int(X.numel()/X[1].numel()), 1, requires_grad=True)
   def LinearReg(X):
      y = X.float() @ self.w.transpose(0,1) + self.b
      return self.y

   def rmse(self,y,y_hat):
      return torch.sqrt(((torch.pow(self.y-self.y_hat,2))/torch.numel(self.y)).sum())

   def fit(self,X):
      learning_rate = 0.01
      for i in range(300):
         y_hat = LinearReg(X)
         loss = rmse(self.y,y_hat)
         loss.backward()
         with torch.no_grad():
            w -= learning_rate * self.w.grad
            b -= learning_rate * self.b.grad
            self.w.grad = None
            self.b.grad = None


In [40]:
y.unsqueeze(1)

tensor([[151.],
        [ 75.],
        [141.],
        [206.],
        [135.],
        [ 97.],
        [138.],
        [ 63.],
        [110.],
        [310.],
        [101.],
        [ 69.],
        [179.],
        [185.],
        [118.],
        [171.],
        [166.],
        [144.],
        [ 97.],
        [168.],
        [ 68.],
        [ 49.],
        [ 68.],
        [245.],
        [184.],
        [202.],
        [137.],
        [ 85.],
        [131.],
        [283.],
        [129.],
        [ 59.],
        [341.],
        [ 87.],
        [ 65.],
        [102.],
        [265.],
        [276.],
        [252.],
        [ 90.],
        [100.],
        [ 55.],
        [ 61.],
        [ 92.],
        [259.],
        [ 53.],
        [190.],
        [142.],
        [ 75.],
        [142.],
        [155.],
        [225.],
        [ 59.],
        [104.],
        [182.],
        [128.],
        [ 52.],
        [ 37.],
        [170.],
        [170.],
        [ 61.],
        [144.],
        